version: 2
jobs:
  test-3.6: &full-test-template
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: create virtualenv
          command: |
            python -m virtualenv env

      - run: &install-dependencies-template
          name: install dependencies
          command: |
            . env/bin/activate
            python --version
            pip install -r tests/requirements.txt --extra-index-url https://pypi.dwavesys.com/simple

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: &run-tests-template
          name: run unittests
          command: |
            . env/bin/activate
            python --version
            coverage run -m unittest discover

  test-3.5:
    <<: *full-test-template
    docker:
      - image: circleci/python:3.5-jessie

  test-3.4:
    <<: *full-test-template
    docker:
      - image: circleci/python:3.4-jessie

  test-2.7:
    <<: *full-test-template
    docker:
      - image: circleci/python:2.7-jessie

  test-osx:
    macos:
      xcode: "9.0"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install pyenv
          command: |
            brew install pyenv

      - restore_cache:
          keys:
          - pyenv-versions-{{ .Environment.CIRCLE_JOB }}
          - dependencies2.7-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: install python 2.7.14 and 3.6.5 with pyenv
          command: |
            pyenv install 2.7.14 -s
            pyenv install 3.6.5 -s

      - save_cache:
          paths:
            - ~/.pyenv
          key: pyenv-versions-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: create virtualenv for 2.7.14
          command: |
            eval "$(pyenv init -)"
            pyenv local 2.7.14
            python -m pip install virtualenv
            python -m virtualenv env

      - run: *install-dependencies-template

      - save_cache:
          paths:
            - ./env
          key: dependencies2.7-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *run-tests-template

      - run:
          name: clear virtual environment
          command: |
            rm -rf env

      - restore_cache:
          keys:
          - dependencies3.6-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: create virtualenv for 3.6.5
          command: |
            eval "$(pyenv init -)"
            pyenv local 3.6.5
            python -m pip install virtualenv
            python -m virtualenv env

      - run: *install-dependencies-template

      - save_cache:
          paths:
            - ./env
          key: dependencies3.6-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *run-tests-template

workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-2.7
      - test-3.5
      - test-3.4
      - test-osx:
          requires:
            - test-3.6
            - test-2.7
            - test-3.5
            - test-3.4
